### ISSUE TITLE
Not working on Ubuntu 22.04.3

### ISSUE THREAD

**Issue by aria3ppp** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#17]
Ubuntu 22.04.3 LTS
Gnome 42.9
X11
nvidia-driver-535 installed

Let me know to share more information about my setup

**Comment by thiagobraga** [comment]
Hi @aria3ppp. I have the same setup as you:

![image](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/assets/993684/6950d2be-14b0-4a40-b4b1-86bffe4ce325)

And the extension worked for me.
- I was scrolling inside Chrome with VScode open behind it
- Then, I Alt + Tab to VScode
- And do a scroll inside VScode
- The scroll action was being repeated inside VScode. This was so annoying.

After I installed the extension, it worked flawlessly.

**Comment by lucasresck** [comment]
Thank you, @aria3ppp and @thiagobraga, for sharing your experiences with the extension.

@aria3ppp, does the extension still not work for you?

**Comment by lucasresck** [comment]
I'll close this issue, feel free to reopen it or create another issue if necessary.

**Comment by aria3ppp** [comment]
Sorry for the late response @thiagobraga, @lucasresck.
Maybe i should check out other extensions on my list i guess
![Screenshot from 2023-12-24 09-57-23](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/assets/111690399/f3515863-bfeb-4bc1-904d-76a6c3313fc5)

**Comment by lucasresck** [comment]
@aria3ppp, please, try deactivating the other extensions (especially the Coverflow Alt-Tab extension) and check if this one works. Let me know!

**Comment by aria3ppp** [comment]
> @aria3ppp, please, try deactivating the other extensions (especially the Coverflow Alt-Tab extension) and check if this one works. Let me know!

Ah that's correct. I disabled Coverflow Alt+Tab and now Scroll Workaround literally works.
Now i cannot use Coverflow Alt+Tab anymore.
What do you think? should i check this issue on Coverflow Alt+Tab repo or you can fix this on here?

**Comment by lucasresck** [comment]
That's an interesting finding, thank you!

It seems both extensions have some intersection and conflict. I don't think this is necessarily a problem of either extension; the problem itself is the GNOME bug being approached here.

I think the ideal solution---besides properly solving this GNOME bug--- would be requesting this to be included in the Coverflow Alt+Tab extension. This is because they provide a novel approach for app switching, they could be able to cover this issue too.

I took a look at their code and it seems quite dense, I'm not sure how difficult it is to incorporate this solution there. My suggestion is opening an issue at their extension (you may mention me there) and we can try to advance this.

I'm happy at least to see the extension works for you. I'll close the issue as a matter of organization, but we may continue the discussion here, at another issue, or at the Coverflow Alt+Tab repo.

Thank you!
