### ISSUE TITLE
Error When Making Extension

### ISSUE THREAD

**Issue by machineghost** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#3]
> $ make install
> gnome-extensions pack -f .
> make: gnome-extensions: Command not found
> make: *** [Makefile:7: pack] Error 127

It seems perhaps the readme is missing some sort of `sudo apt-get install gnome-extensions` step?

**Comment by lucasresck** [comment]
Hi, thanks for reaching out!

[`gnome-extensions` is a command provided by the package `gnome-shell`](https://manpages.ubuntu.com/manpages/jammy/man1/gnome-extensions.1.html), which is the GNOME graphical shell itself. Could you please provide more information about your Linux distro, distro version, and GNOME version? Thank you!

**Comment by machineghost** [comment]
Linux Mint, MATE, 20.3 (... and whatever version of MATE/GNOME comes with it ... not sure how to check the exact GNOME version).

I'm *guessing* on my system you'd want the package `gnome-shell-extensions` (and dependant packages `gnome-shell-extensions-prefs` and `chrome-gnome-shell`)?  When I installed those three I got:

>$ make install
>gnome-extensions pack -f .
>gnome-extensions install -f alt-tab-scroll-workaround@lucasresck.shell-extension.zip

(ie. no error).

**Comment by lucasresck** [comment]
Oh, I see, so you're not using GNOME. MATE and GNOME are different shells (although one is based on a past version of the other), I don't think `README` should cover the installation of the extension in other shells (didn't know it was possible!).

I'm assuming someone with the intention to use a GNOME Shell extension in other graphical interfaces would work on having these extensions functioning at first. But nice to know it can be used this way. Does it workaround the scroll problem?

**Comment by machineghost** [comment]
>Does it workaround the scroll problem?

Unfortunately no :(  It seems like it's happening less, but with an irregular bug like that it's hard to say for sure.

**Comment by lucasresck** [comment]
Sad to hear that.

The bug shouldn't be irregular, I mean, scroll Chrome, `Alt+Tab` to VS Code, and the scroll should be repeated. Please, also take a look at https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/2, it could be your case, although I'm not sure how things work on MATE.

I'll close this issue because the subject itself (error with `make`) is ended but we can continue this discussion in another issue (at this repo or at https://github.com/microsoft/vscode/issues/28795). Also fell free to reopen this if necessary.
