### ISSUE TITLE
Fixes issue only for Alt+Tab, but not for Alt+Esc

### ISSUE THREAD

**Issue by tsoj** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#33]
System: Kernel: 6.5.0-25-generic x86_64 bits: 64 Desktop: GNOME 42.9 Distro: Ubuntu 22.04.4 LTS (Jammy Jellyfish)

It seems like this extension fixes the issue when switching windows with Alt+Tab, but when switching with Alt+Esc (for example between VSCode and Chrome windows) it still has the scrolling bug.

I installed version 4 with the Extension Manager.

**Comment by lucasresck** [comment]
Hi, @tsoj! Thanks for pointing this out!

The fix for `Alt+Esc` was included in [`v5`](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/releases/tag/v5), which also included the extension's support of GNOME 45 and a few other bugs. `v5` only supports GNOME 45+, which is the default for newer Ubuntu versions.

Currently, there is an open issue to include `Alt+Esc`  fix into `v4`: https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/23. This was not worked out yet because it would mean solving an issue for an older version of the tool; for instance, Ubuntu 24.04 LTS is about to be released and it will include GNOME 45+.

However, it is possible to include an `Alt+Esc` fix to `v4` without much effort. This would mean repeating what is done to `WindowSwitcherPopup` and `AppSwitcherPopup` in `v4`'s [`extension.js`](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/blob/195de2de6db5b661f4ca896ce7fd4eae786c30d1/extension.js) to `WindowCyclerPopup` as well—as in https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/27/commits/acf99216e78dc87e963af9bb76c1e7f5df684517.

I will close this issue as it duplicates the issue https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/23. Feel free to comment it here or there if needed!
