### ISSUE TITLE
Enhance README with Gnome version compatibility

### ISSUE THREAD

**Issue by clement-schwartz** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#40]
Hello,

I installed your extension and I'm very happy with it, solving the scrolling issue as expected :ok_hand: .

The installation wasn't working initially and it took me a while to figure out why.
I have Gnome 42.9, and the last current version (v8) of your extension only supports from Gnome 45.

V1 = 42
V2, V3 = 42, 43
V4 = 42, 43, 44
V5, V6 = 45
V7 = 45, 46
V8 = 45, 46, 47

This could be explained in README, to say user to check it's Gnome version first and checkout to the correct version.

Let me know if you want me to open a PR, which would be my first contribution ever on any project :smile: 
Gnome Version ==> Extension Version to install
42 ==> V4
43 ==> V4
44 ==> V4
45 ==> V8
46 ==> V8
47 ==> V8

And thanks again for this workaround to a very annoying issue.

**Comment by lucasresck** [comment]
Hi, @clement-schwartz, thanks for getting in touch!

You're right, current instructions don't cover version support. Please, feel free to submit a PR!

**Comment by lucasresck** [comment]
@clement-schwartz, something just came to my mind: `v4` is a little bit limited in terms of support for different versions of the `Alt+Tab` issue, in particular [`Alt+Esc`](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/23) and [overview + mouse](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/26). These issues were fixed in `v5+` (https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/21, https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/25) but older versions of GNOME (< 45) didn't receive the fixes. The solutions for `v5` cannot be applied directly to `v4` because GNOME 45 had a significant update.

Maybe you are interested in working on these open issues 😀 I think it is simple to convert the solutions of `Alt+Esc` and overview + mouse from `v5` to `v4` inspiring from the solutions for `Alt+Tab` and `Super+Tab` in `v4`.
