### ISSUE TITLE
Extension is incompatible with GNOME version 43

### ISSUE THREAD

**Issue by FrankSansC** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#5]
![Screenshot from 2022-10-06 13-38-08](https://user-images.githubusercontent.com/3471406/194303271-d667070a-8307-4b95-b509-00971c0e505b.png)

**Comment by lucasresck** [comment]
Hi there,

I can't test the extension on GNOME 43 because my GNOME version is 42, however I believe you can manually change the version in the file [`metadata.json`](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/blob/db2a5f8f83559b65adc9c41ee98a1b9d851971a6/metadata.json#L6) and test it to see if it works.

If you do this, please let me know!

**Comment by FrankSansC** [comment]
@lucasresck thanks for your answer. I've tested and, as far as I can tell, it works properly. Do you want me to do a PR with the modification to `metadata.json` ?

**Comment by lucasresck** [comment]
Please, it would be awesome. Thank you!
